      ///////is?NOT??OIBN0ekl-;                                                      141111/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_Prompt */

#ifndef _Included_jni_Prompt
#define _Included_jni_Prompt
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_Prompt
 * Method:    getLine
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jni_Prompt_getLine
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
